# Generated by Django 3.1.14 on 2022-01-11 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220104_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
