# Generated by Django 3.1.14 on 2022-01-11 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_question_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
